export default {
  Berlin: "Berlin Brandenburg (BER)",
  Paris: "Paris Charles de Gaulle (CDG)",
  London: "London Heathrow (LHR)",
  Madrid: "Madrid Barajas (MAD)",
  Rome: "Rome Fiumicino (FCO)",
  Bucharest: "Bucharest Henri Coandă (OTP)",
  Vienna: "Vienna International (VIE)",
  Hamburg: "Hamburg Airport (HAM)",
  Warsaw: "Warsaw Chopin (WAW)",
  Budapest: "Budapest Ferenc Liszt (BUD)",
  Munich: "Munich Airport (MUC)",
  Barcelona: "Barcelona El Prat (BCN)",
  Cologne: "Cologne Bonn (CGN)",
  Milan: "Milan Malpensa (MXP)",
  Amsterdam: "Amsterdam Schiphol (AMS)",
  "Frankfurt am Main": "Frankfurt am Main (FRA)",
  Prague: "Prague Václav Havel (PRG)",
  Lisbon: "Lisbon Humberto Delgado (LIS)",
  Stuttgart: "Stuttgart Airport (STR)",
  Düsseldorf: "Düsseldorf Airport (DUS)",
  Copenhagen: "Copenhagen Kastrup (CPH)",
  Brussels: "Brussels Airport (BRU)",
  Helsinki: "Helsinki Vantaa (HEL)",
  Oslo: "Oslo Gardermoen (OSL)",
  Zurich: "Zurich Airport (ZRH)",
  Stockholm: "Stockholm Arlanda (ARN)",
  Athens: "Athens Eleftherios Venizelos (ATH)",
  Dublin: "Dublin Airport (DUB)",
  Edinburgh: "Edinburgh Airport (EDI)",
  Kraków: "Kraków John Paul II (KRK)",
  Florence: "Florence Peretola (FLR)",
  Venice: "Venice Marco Polo (VCE)",

  Lindfurt: "Lindfurt International Airport (LFR)", // fake

  Nice: "Nice Côte d'Azur (NCE)",
  Porto: "Porto Francisco Sá Carneiro (OPO)",
  Valencia: "Valencia Airport (VLC)",
  Seville: "Seville Airport (SVQ)",
  Tallinn: "Tallinn Airport (TLL)",
  Riga: "Riga International (RIX)",
  Vilnius: "Vilnius Airport (VNO)",
  Ljubljana: "Ljubljana Jože Pučnik (LJU)",
  Bratislava: "Bratislava Airport (BTS)",
  Reykjavík: "Reykjavík Keflavík (KEF)",
  Leipzig: "Leipzig/Halle (LEJ)",
  Dortmund: "Dortmund Airport (DTM)",
  Bremen: "Bremen Airport (BRE)",
  Dresden: "Dresden Airport (DRS)",
  Nuremberg: "Nuremberg Airport (NUE)",
  Hanover: "Hannover Airport (HAJ)",
  Friedrichshafen: "Friedrichshafen Airport (FDH)",
  Münster: "Münster Osnabrück (FMO)",
  Karlsruhe: "Karlsruhe/Baden-Baden (FKB)",
  Saarbrücken: "Saarbrücken Airport (SCN)",
  Erfurt: "Erfurt–Weimar (ERF)",
  Rostock: "Rostock–Laage (RLG)",
  Kassel: "Kassel Airport (KSF)",
  Memmingen: "Memmingen Airport (FMM)",
  Aachen: "Cologne Bonn (CGN)",
  Aalen: "Stuttgart Airport (STR)",
  Ahlen: "Dortmund Airport (DTM)",
  Arnsberg: "Dortmund Airport (DTM)",
  Aschaffenburg: "Frankfurt am Main (FRA)",
  Augsburg: "Munich Airport (MUC)",
  "Bad Homburg v. d. Höhe": "Frankfurt am Main (FRA)",
  "Bad Kreuznach": "Frankfurt-Hahn (HHN)",
  "Bad Salzuflen": "Paderborn Lippstadt (PAD)",
  "Baden-Baden": "Karlsruhe/Baden-Baden (FKB)",
  Bamberg: "Nuremberg Airport (NUE)",
  Bayreuth: "Nuremberg Airport (NUE)",
  Bergheim: "Cologne Bonn (CGN)",
  "Bergisch Gladbach": "Cologne Bonn (CGN)",
  Bielefeld: "Paderborn Lippstadt (PAD)",
  Bocholt: "Düsseldorf Airport (DUS)",
  Bochum: "Dortmund Airport (DTM)",
  Bonn: "Cologne Bonn (CGN)",
  Bottrop: "Düsseldorf Airport (DUS)",
  "Brandenburg an der Havel": "Berlin Brandenburg (BER)",
  Braunschweig: "Hannover Airport (HAJ)",
  Bremenhaven: "Bremen Airport (BRE)",
  "Castrop-Rauxel": "Dortmund Airport (DTM)",
  Celle: "Hannover Airport (HAJ)",
  Chemnitz: "Dresden Airport (DRS)",
  Coburg: "Nuremberg Airport (NUE)",
  Constance: "Zurich Airport (ZRH)",
  "Cottbus/Chóśebuz": "Berlin Brandenburg (BER)",
  Delmenhorst: "Bremen Airport (BRE)",
  "Dessau-Roßlau": "Leipzig/Halle (LEJ)",
  Detmold: "Paderborn Lippstadt (PAD)",
  Dinslaken: "Düsseldorf Airport (DUS)",
  Dorsten: "Düsseldorf Airport (DUS)",
  Duisburg: "Düsseldorf Airport (DUS)",
  Düren: "Cologne Bonn (CGN)",
  Erlangen: "Nuremberg Airport (NUE)",
  Eschweiler: "Cologne Bonn (CGN)",
  "Esslingen am Neckar": "Stuttgart Airport (STR)",
  Flensburg: "Hamburg Airport (HAM)",
  "Frankfurt (Oder)": "Berlin Brandenburg (BER)",
  Frechen: "Cologne Bonn (CGN)",
  "Freiburg im Breisgau": "Zurich Airport (ZRH)",
  Fürth: "Nuremberg Airport (NUE)",
  Garbsen: "Hannover Airport (HAJ)",
  Gelsenkirchen: "Düsseldorf Airport (DUS)",
  Gera: "Leipzig/Halle (LEJ)",
  Giessen: "Frankfurt am Main (FRA)",
  Gladbeck: "Düsseldorf Airport (DUS)",
  Göppingen: "Stuttgart Airport (STR)",
  Görlitz: "Dresden Airport (DRS)",
  Greifswald: "Rostock–Laage (RLG)",
  Grevenbroich: "Düsseldorf Airport (DUS)",
  Gummersbach: "Cologne Bonn (CGN)",
  Gütersloh: "Paderborn Lippstadt (PAD)",
};
