export const cities = [
  "Berlin",
  "Hamburg",
  "Munich",
  "Cologne",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Bremen",
  "Dresden",
  "Hanover",
  "Nuremberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Mannheim",
  "Karlsruhe",
  "Augsburg",
  "Wiesbaden",
  "Mönchengladbach",
  "Gelsenkirchen",
  "Aachen",
  "Brunswick",
  "Kiel",
  "Chemnitz",
  "Halle (Saale)",
  "Magdeburg",
  "Freiburg im Breisgau",
  "Krefeld",
  "Mainz",
  "Lübeck",
  "Erfurt",
  "Oberhausen",
  "Rostock",
  "Kassel",
  "Hagen",
  "Potsdam",
  "Saarbrücken",
  "Hamm",
  "Ludwigshafen am Rhein",
  "Mülheim an der Ruhr",
  "Oldenburg",
  "Osnabrück",
  "Leverkusen",
  "Solingen",
  "Darmstadt",
  "Heidelberg",
  "Herne city",
  "Neuss",
  "Regensburg",
  "Paderborn",
  "Ingolstadt",
  "Offenbach am Main",
  "Fürth",
  "Würzburg",
  "Heilbronn",
  "Ulm",
  "Pforzheim",
  "Wolfsburg",
  "Bottrop",
  "Göttingen",
  "Reutlingen",
  "Bremerhaven",
  "Koblenz",
  "Erlangen",
  "Bergisch Gladbach",
  "Remscheid",
  "Jena",
  "Recklinghausen",
  "Trier",
  "Salzgitter",
  "Moers",
  "Siegen",
  "Hildesheim",
  "Gütersloh",
  "Kaiserslautern",
  "Cottbus/Chóśebuz",
  "Hanau",
  "Witten",
  "Schwerin",
  "Ludwigsburg",
  "Esslingen am Neckar",
  "Gera",
  "Iserlohn",
  "Düren",
  "Tübingen",
  "Giessen",
  "Flensburg",
  "Zwickau",
  "Ratingen",
  "Lünen",
  "Villingen-Schwenningen",
  "Constance",
  "Marl",
  "Worms",
  "Minden",
  "Velbert",
  "Neumünster",
  "Dessau-Roßlau",
  "Norderstedt",
  "Delmenhorst",
  "Viersen",
  "Bamberg",
  "Marburg",
  "Rheine",
  "Gladbeck",
  "Lüneburg",
  "Wilhelmshaven",
  "Troisdorf",
  "Dorsten",
  "Detmold",
  "Bayreuth",
  "Arnsberg",
  "Castrop-Rauxel",
  "Landshut",
  "Brandenburg an der Havel",
  "Lüdenscheid",
  "Bocholt",
  "Aschaffenburg",
  "Celle",
  "Kempten",
  "Aalen",
  "Fulda",
  "Lippstadt",
  "Dinslaken",
  "Herford",
  "Rüsselsheim am Main",
  "Kerpen",
  "Weimar",
  "Neuwied",
  "Sindelfingen",
  "Dormagen",
  "Plauen",
  "Grevenbroich",
  "Rosenheim",
  "Neubrandenburg",
  "Herten",
  "Bergheim",
  "Friedrichshafen",
  "Schwäbisch Gmünd",
  "Garbsen",
  "Offenburg",
  "Wesel",
  "Hürth",
  "Greifswald",
  "Stralsund",
  "Langenfeld",
  "Neu-Ulm",
  "Unna",
  "Euskirchen",
  "Göppingen",
  "Hamelin",
  "Frankfurt (Oder)",
  "Meerbusch",
  "Stolberg",
  "Eschweiler",
  "Görlitz",
  "Sankt Augustin",
  "Waiblingen",
  "Baden-Baden",
  "Hilden",
  "Lingen (Ems)",
  "Langenhagen",
  "Pulheim",
  "Hattingen",
  "Bad Salzuflen",
  "Bad Homburg v. d. Höhe",
  "Nordhorn",
  "Schweinfurt",
  "Neustadt an der Weinstraße",
  "Wetzlar",
  "Ahlen",
  "Menden",
  "Passau",
  "Kleve",
  "Wolfenbüttel",
  "Frechen",
  "Ibbenbüren",
  "Bad Kreuznach",
  "Gummersbach",
  "Ravensburg",
  "Speyer",
  "Willich",
  "Peine",
  "Goslar",
  "Rastatt",
  "Böblingen",
  "Erftstadt",
];
