import { type Site } from "./studyData";

const info = {
  hotels: {
    name: "hotels",
  },
  flights: {
    name: "flights",
  },
  cars: {
    name: "cars",
  },
};

const texts = {
  hotels: {
    title: "Wanderlust Hotels",
    item_name: "hotel",
    headerItems: [
      { icon: "faBed", label: "Stays" },
      { icon: "faClock", label: "Long stays" },
      { icon: "faTag", label: "Deals" },
      { icon: "faMapMarkerAlt", label: "Attractions" },
      { icon: "faBook", label: "City guides" },
    ],
    listYourOfferText: "List your property",
    slogan: "Wanderlust days and cozy nights",
    description: "Choose from cabins, houses, and more",
    searchItemTitle: "See availability",
    searchItemTaxi: "Free airport taxi",
    searchItemCancellationTitle: "Free cancellation",
    searchItemCancellationText:
      "You can cancel later, so lock in this great price today!",
    searchItemReviews: "reviews",
    searchItemNightsGuests: "night, adult", // Used for pluralization
    searchItemIncludes: "Includes taxes and fees",
    searchItemFromCenter: "from center",
    searchItemPricePrefix: "€",
    searchItemSeeAvailability: "See availability",
    exploreButton: "Explore vacation rentals",
    locationInputs: [
      { key: "destination", label: "Where are you going?", icon: "faBed" },
    ],
    searchOptions: [],
    searchButton: "Search",
    counts: {
      adult: "adult",
      child: "child",
      room: "room",
    },
    offersTitle: "Offers",
    longStayTitle: "Take your longest vacation yet",
    longStayText:
      "Browse properties offering long-term stays, many at reduced monthly rates",
    longStayButton: "Find a stay",
    dreamVacationTitle: "Fly away to your dream vacation",
    dreamVacationText:
      "Get inspired – compare and book flights with flexibility",
    dreamVacationButton: "Search for flights",
    typesTitle: "Browse by property type",
    typesList: [
      { name: "Hotels", count: "233" },
      { name: "Apartments", count: "2331" },
      { name: "Resorts", count: "2331" },
      { name: "Villas", count: "2331" },
      { name: "Cabins", count: "2331" },
    ],
    citiesTitle: "Popular cities",
    citiesList: [
      {
        name: "Dublin",
        count: "123 properties",
      },
      {
        name: "Reno",
        count: "533 properties",
      },
      {
        name: "Austin",
        count: "532 properties",
      },
    ],
    lovedTitle: "Homes guests love",
    lovedList: [
      {
        name: "Aparthotel Stare Miasto",
        city: "Madrid",
        price: "from € 120",
        rating: "8.9",
        ratingText: "Excellent",
      },
      {
        name: "Comfort Suites Airport",
        city: "Austin",
        price: "from € 140",
        rating: "9.3",
        ratingText: "Exceptional",
      },
      {
        name: "Four Seasons Hotel",
        city: "Lisbon",
        price: "from € 99",
        rating: "8.8",
        ratingText: "Excellent",
      },
      {
        name: "Hilton Garden Inn",
        city: "Berlin",
        price: "from € 105",
        rating: "8.9",
        ratingText: "Excellent",
      },
    ],
    detail: {
      reserveButton: "Reserve Now",
      pageTitle: ({ name }) => `Your stay at ${name}`,
      introLine: ({ name }) =>
        `${name} has accommodations with air conditioning and free WiFi.\n\nA buffet breakfast is served daily. The restaurant is open from 19:00 to 22:00 Monday to Friday.\n\nFree private parking is available.`,
      locationNote: ({ metersFromCenter }) =>
        `Good location – ${metersFromCenter} from center`,
      pricePromo:
        "Book a stay over € 114 at this property and get a free airport taxi",
      availabilityHeading: "Availability",
      badgeBreakfast: "Good breakfast included",
      badgeCancellation: (date) =>
        `Free cancellation before 6:00 PM on ${date}`,
      badgePayLater: (date) => `Pay nothing until ${date}`,
      packageTitle: "Your package:",
    },
  },
  flights: {
    title: "SkyWay Flights",
    item_name: "flight",
    headerItems: [
      { icon: "faPlane", label: "Flights" },
      { icon: "faTags", label: "Flight deals" },
      { icon: "faSuitcaseRolling", label: "Baggage info" },
      { icon: "faShieldAlt", label: "Travel insurance" },
      { icon: "faInfoCircle", label: "Flight status" },
    ],
    listYourOfferText: "Join our partner program",
    slogan: "Smooth skies and easy journeys",
    description: "Book domestic and international flights with ease",
    exploreButton: "Explore flight options",
    locationInputs: [
      { key: "origin", label: "Where from?", icon: "faPlaneDeparture" },
      { key: "destination", label: "Where to?", icon: "faPlaneArrival" },
    ],
    searchOptions: [
      {
        label: "Round-trip",
        checked: true,
      },
      {
        label: "Direct flights only",
      },
    ],
    searchButton: "Search",
    counts: {
      adult: "adult",
      child: "child",
    },
    offersTitle: "Flight Deals",
    longStayTitle: "Plan your extended getaway",
    longStayText: "Discover flight options for longer trips at great prices",
    longStayButton: "Find a flight",
    dreamVacationTitle: "Soar to your dream destination",
    dreamVacationText: "Explore and book flights with the best deals",
    dreamVacationButton: "Search flights now",
    typesTitle: "Browse by flight type",
    typesList: [
      { name: "Non-stop", count: "1280" },
      { name: "One-way", count: "1124" },
      { name: "Round-trip", count: "980" },
      { name: "Multi-city", count: "432" },
    ],
    citiesTitle: "Top destinations",
    citiesList: [
      { name: "New York", count: "1200 flights" },
      { name: "Los Angeles", count: "980 flights" },
      { name: "Chicago", count: "875 flights" },
    ],
    lovedTitle: "Flights travelers love",

    detail: {
      reserveButton: "Reserve Now",
      pageTitle: ({ name }) => `Your stay at ${name}`,
      introLine: ({ name }) =>
        `${name} has accommodations with air conditioning and free WiFi.\n\nA buffet breakfast is served daily. The restaurant is open from 19:00 to 22:00 Monday to Friday.\n\nFree private parking is available.`,
      locationNote: ({ metersFromCenter }) =>
        `Earn up to 116 SkyPoints with this flight!`,
      // pricePromo: "Earn up to 116 SkyPoints with this flight!",
      // availabilityHeading: "Availability",
      badgeBreakfast: "Good breakfast included",
      badgeCancellation: (date) =>
        `Free cancellation before 6:00 PM on ${date}`,
      badgePayLater: (date) => `Pay nothing until ${date}`,
      packageTitle: "Your package:",
    },
  },
  cars: {
    title: "Overdrive Car Rentals",
    item_name: "car",
    headerItems: [
      { icon: "faCar", label: "Car rentals" },
      { icon: "faRoute", label: "One-way rentals" },
      { icon: "faBolt", label: "Luxury & electric" },
      { icon: "faMapMarkedAlt", label: "Scenic routes" },
      { icon: "faShieldAlt", label: "Insurance & protection" },
    ],
    listYourOfferText: "Sign in",
    slogan: "Your ride, your freedom",
    description: "Find the perfect rental for your trip",
    locationInputs: [
      { key: "origin", label: "Pickup location", icon: "faCar" },
      { key: "destination" },
    ],
    searchOptions: [
      {
        label: "same return location",
        checked: true,
      },
    ],
    exploreButton: "Browse car rentals",
    searchButton: "Search cars",
    counts: {},
    offersTitle: "Rental Deals",
    longStayTitle: "Drive longer, save more",
    longStayText: "Check out cars for extended rentals with special rates",
    longStayButton: "Find a car",
    dreamVacationTitle: "Unforgettable road trips start here",
    dreamVacationText:
      "Discover hidden gems and scenic routes with the perfect ride",
    dreamVacationButton: "Search for rentals",
    typesTitle: "Browse by vehicle type",
    typesList: [
      { name: "Compact", count: "670" },
      { name: "SUV", count: "550" },
      { name: "Luxury", count: "210" },
      { name: "Electric", count: "160" },
      { name: "Vans", count: "300" },
    ],
    citiesTitle: "Popular pickup locations",
    citiesList: [
      { name: "Miami", count: "320 rentals" },
      { name: "San Francisco", count: "450 rentals" },
      { name: "Denver", count: "390 rentals" },
    ],
    lovedTitle: "Cars renters love",
    detail: {
      reserveButton: "Reserve Now",
      pageTitle: ({ name }) => `Your stay at ${name}`,
      introLine: ({ name }) =>
        `${name} has accommodations with air conditioning and free WiFi.\n\nA buffet breakfast is served daily. The restaurant is open from 19:00 to 22:00 Monday to Friday.\n\nFree private parking is available.`,
      locationNote: ({ metersFromCenter }) =>
        `Good location – ${metersFromCenter} from center`,
      pricePromo: "✓ 400 km included",
      availabilityHeading: "Availability",
      badgeBreakfast: "Good breakfast included",
      badgeCancellation: (date) =>
        `Free cancellation before 6:00 PM on ${date}`,
      badgePayLater: (date) => `Pay nothing until ${date}`,
      packageTitle: "Your package:",
    },
  },
};

const mocks = {
  hotels: [
    {
      name: "Hotel Residenz",
      location: "Westend",
      metersFromCenter: "3.8 km",
      price: 68,
      prevPrice: 75,
      rating: 8.6,
      numReviews: 2502,
      comfort: 9.4,
      description:
        "Contemporary living, sleek hotel, stylish rooms, top-notch amenities.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "CitySmart Hotels Stadion",
      location: "Am Stadion",
      metersFromCenter: "4.2 km",
      price: 75,
      rating: 9.0,
      numReviews: 984,
      comfort: 9.4,
      description: "Style in simplicity, minimalist design, maximum comfort.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Hotel Schlossblick",
      location: "Am Schlosspark",
      metersFromCenter: "2.4 km",
      price: 84,
      rating: 9.7,
      numReviews: 2991,
      comfort: 8.6,
      description:
        "Refined luxury, sophisticated setting, exquisite accommodations, impeccable service.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "The Nordic Inn",
      location: "Markt",
      metersFromCenter: "1.5 km",
      price: 83,
      rating: 8.4,
      numReviews: 2140,
      comfort: 9.5,
      description:
        "Tranquility in a peaceful space, where comfort meets simplicity.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Mitor Hotel Mitte",
      location: "Mitte",
      metersFromCenter: "2.8 km",
      price: 56,
      prevPrice: 66,
      rating: 8.6,
      numReviews: 1139,
      comfort: 9.9,
      description:
        "Classic charm, welcoming establishment, timeless hospitality, cozy accommodations.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "City Palace",
      location: "Westend",
      metersFromCenter: "3.6 km",
      price: 79,
      rating: 7.5,
      numReviews: 2104,
      comfort: 9.5,
      description:
        "Escape to modernity, chic urban destination, cutting-edge design, vibrant atmosphere.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Le petit logement",
      location: "Stadtmitte",
      metersFromCenter: "1 km",
      price: 59,
      rating: 8.4,
      numReviews: 2140,
      comfort: 9.1,
      description: "Cozy stay, comfortable suites, warmth, relaxation.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Hotel Domicil",
      location: "Südende",
      metersFromCenter: "4.4 km",
      price: 81,
      rating: 9.8,
      numReviews: 2498,
      comfort: 9,
      description:
        "Effortless sophistication, refined elegance, impeccable details.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Stella Hotel",
      location: "Westend",
      metersFromCenter: "4.7 km",
      price: 63,
      rating: 7.7,
      numReviews: 1036,
      comfort: 9.3,
      description:
        "Unwind in understated luxury, quiet escape, indulgent accommodations.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Kükennest",
      location: "Zoologischer Garten",
      metersFromCenter: "2.7 km",
      price: 84,
      rating: 8.7,
      numReviews: 1829,
      comfort: 8.8,
      description:
        "Recharge in relaxed accommodations, laid-back vibes, modern convenience.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
  ],
  flights: [
    {
      airline: "Lufthansa",
      departureTime: "07:10",
      arrivalTime: "09:00",
      departureTimeReturn: "17:45",
      arrivalTimeReturn: "19:35",
      duration: "1h 50m",
      stops: "direct",
      price: 89,
    },
    {
      airline: "easyJet",
      departureTime: "12:30",
      arrivalTime: "14:20",
      departureTimeReturn: "20:15",
      arrivalTimeReturn: "22:05",
      duration: "1h 50m",
      stops: "direct",
      price: 102,
    },
    {
      airline: "Eurowings",
      departureTime: "16:00",
      arrivalTime: "17:50",
      departureTimeReturn: "10:30",
      arrivalTimeReturn: "12:20",
      duration: "1h 50m",
      stops: "direct",
      price: 76,
    },
    {
      airline: "KLM",
      departureTime: "10:15",
      arrivalTime: "12:05",
      departureTimeReturn: "18:00",
      arrivalTimeReturn: "19:50",
      duration: "1h 50m",
      stops: "direct",
      price: 95,
    },
    {
      airline: "Austrian Airlines",
      departureTime: "06:50",
      arrivalTime: "08:30",
      departureTimeReturn: "16:30",
      arrivalTimeReturn: "18:10",
      duration: "1h 40m",
      stops: "Direct",
      price: 88,
    },
    {
      airline: "Air France",
      departureTime: "13:45",
      arrivalTime: "15:35",
      departureTimeReturn: "21:00",
      arrivalTimeReturn: "22:50",
      duration: "1h 50m",
      stops: "Direct",
      price: 99,
    },
    {
      airline: "Condor",
      departureTime: "08:20",
      arrivalTime: "10:10",
      departureTimeReturn: "16:45",
      arrivalTimeReturn: "18:35",
      duration: "1h 50m",
      stops: "Direct",
      price: 82,
    },
    {
      airline: "Lufthansa",
      departureTime: "15:10",
      arrivalTime: "17:00",
      departureTimeReturn: "11:00",
      arrivalTimeReturn: "12:50",
      duration: "1h 50m",
      stops: "Direct",
      price: 91,
    },
    {
      airline: "Luxair",
      departureTime: "09:05",
      arrivalTime: "11:05",
      departureTimeReturn: "18:30",
      arrivalTimeReturn: "20:30",
      duration: "2h 00m",
      stops: "Direct",
      price: 87,
    },
    {
      airline: "Eurowings",
      departureTime: "18:40",
      arrivalTime: "20:30",
      departureTimeReturn: "12:15",
      arrivalTimeReturn: "14:05",
      duration: "1h 50m",
      stops: "Direct",
      price: 78,
    },
  ],
  cars: [
    {
      name: "Renault Espace",
      location: "Airport",
      price: 67,
      description: "Family Van - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "renault_espace",
      luggage: 4,
      doors: 4,
    },
    {
      name: "Fiat 500",
      location: "Central Station",
      price: 54,
      description: "Mini Go - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "fiat_500",
      luggage: 1,
      doors: 3,
    },
    {
      name: "VW Polo",
      location: "Central Station",
      price: 51,
      description: "Urban Runner - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "vw_polo",
      luggage: 2,
      doors: 4,
    },
    {
      name: "Hyundai Ioniq",
      location: "Central Station",
      price: 95,
      description: "EcoCruiser - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "hyundai_ioniq",
      luggage: 2,
      doors: 4,
    },
    {
      name: "Jeep Wrangler",
      location: "Central Station",
      price: 57,
      description: "Adventure Pro - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "jeep_wrangler",
      luggage: 3,
      doors: 4,
    },
    {
      name: "Mini Cooper",
      location: "Central Station",
      price: 85,
      description: "City Hopper - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "mini_cooper",
      luggage: 2,
      doors: 3,
    },
    {
      name: "Audi A6",
      location: "Airport",
      price: 72,
      description: "Executive Line - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "audi_a6",
      luggage: 3,
      doors: 4,
    },
    {
      name: "Tesla Model 3",
      location: "Central Station",
      price: 31,
      description:
        "Electric Motion - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "tesla_model_3",
      luggage: 2,
      doors: 4,
    },
    {
      name: "VW Polo",
      location: "Airport",
      price: 54,
      description: "Urban Runner - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "vw_polo",
      luggage: 2,
      doors: 5,
    },
    {
      name: "Jeep Wrangler",
      location: "Airport",
      price: 72,
      description: "Adventure Pro - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: false,
      seats: 5,
      transmission: "automatic",
      fuelPolicy: "Full to full",
      image: "jeep_wrangler",
      luggage: 3,
      doors: 4,
    },
  ],
};

const websitesData = {
  hotels: {
    ...info.hotels,
    ...texts.hotels,
    mocks: mocks.hotels,
  },
  flights: {
    ...info.flights,
    ...texts.flights,
    mocks: mocks.flights,
  },
  cars: {
    ...info.cars,
    ...texts.cars,
    mocks: mocks.cars,
  },
} as const satisfies Record<Site, any>;

export type WebsiteData = (typeof websitesData)[keyof typeof websitesData];
export type HotelData = typeof websitesData.hotels;
export type FlightData = typeof websitesData.flights;
export type CarData = typeof websitesData.cars;
export type AnySiteData = HotelData | FlightData | CarData;

export default websitesData;
