import React from "react";
import { useNavigate } from "react-router-dom";
import { Model } from "survey-core";
import { Survey } from "survey-react-ui";
import "survey-core/defaultV2.min.css";
import { storeJson } from "src/lib/client";
import { useCustomNavigate } from "src/components/NavigationProvider.tsx";

const Demographics: React.FC = () => {
  const navigateDelayed = useCustomNavigate();

  const surveyJson = {
    elements: [
      {
        name: "age",
        title: "What is your age?",
        type: "text",
        inputType: "number",
        min: 0,
        max: 100,
        isRequired: true,
      },
      {
        type: "radiogroup",
        name: "gender",
        title: "Which gender do you identify with?",
        isRequired: true,
        colCount: 1,
        choices: ["Male", "Female", "Other"],
      },
      {
        name: "country",
        title: "What is your country of birth?",
        type: "dropdown",
        isRequired: true,
        choices: [
          "Afghanistan",
          "Angola",
          "Albania",
          "Andorra",
          "Argentina",
          "Armenia",
          "Antigua and Barbuda",
          "Australia",
          "Austria",
          "Azerbaijan",
          "Algeria",
          "Burundi",
          "Belgium",
          "Benin",
          "Burkina Faso",
          "Bangladesh",
          "Bulgaria",
          "Bahrain",
          "Bahamas",
          "Bosnia and Herzegovina",
          "Belarus",
          "Belize",
          "Bolivia",
          "Brazil",
          "Barbados",
          "Brunei",
          "Bhutan",
          "Botswana",
          "Central African Republic",
          "Canada",
          "Chile",
          "China",
          "Cameroon",
          "Colombia",
          "Comoros",
          "Cape Verde",
          "Costa Rica",
          "Cuba",
          "Cyprus",
          "Czechia",
          "Croatia",
          "Cambodia",
          "Chad",
          "DR Congo",
          "Djibouti",
          "Dominica",
          "Denmark",
          "Dominican Republic",
          "Ecuador",
          "Egypt",
          "Eritrea",
          "Estonia",
          "Ethiopia",
          "Equatorial Guinea",
          "El Salvador",
          "Eswatini",
          "Finland",
          "Fiji",
          "France",
          "Germany",
          "Gabon",
          "Georgia",
          "Ghana",
          "Guinea",
          "Gambia",
          "Greece",
          "Grenada",
          "Guatemala",
          "Guyana",
          "Honduras",
          "Haiti",
          "Hungary",
          "Ivory Coast",
          "Indonesia",
          "India",
          "Ireland",
          "Iran",
          "Iraq",
          "Iceland",
          "Israel",
          "Italy",
          "Jamaica",
          "Jordan",
          "Japan",
          "Kazakhstan",
          "Kenya",
          "Kyrgyzstan",
          "Kiribati",
          "Kuwait",
          "Laos",
          "Lebanon",
          "Liberia",
          "Libya",
          "Liechtenstein",
          "Lesotho",
          "Lithuania",
          "Luxembourg",
          "Latvia",
          "Micronesia",
          "Morocco",
          "Monaco",
          "Moldova",
          "Madagascar",
          "Maldives",
          "Mexico",
          "Marshall Islands",
          "Mali",
          "Malta",
          "Myanmar",
          "Montenegro",
          "Mongolia",
          "Mozambique",
          "Mauritania",
          "Mauritius",
          "Malawi",
          "Malaysia",
          "North Macedonia",
          "Namibia",
          "Niger",
          "Nigeria",
          "Nicaragua",
          "Netherlands",
          "Norway",
          "Nepal",
          "Nauru",
          "New Zealand",
          "North Korea",
          "Oman",
          "Pakistan",
          "Panama",
          "Peru",
          "Philippines",
          "Palau",
          "Papua New Guinea",
          "Poland",
          "Portugal",
          "Paraguay",
          "Qatar",
          "Republic of the Congo",
          "Romania",
          "Russia",
          "Rwanda",
          "Switzerland",
          "Spain",
          "Saint Kitts and Nevis",
          "South Korea",
          "Saint Lucia",
          "Sri Lanka",
          "Saudi Arabia",
          "Sudan",
          "Senegal",
          "Singapore",
          "Solomon Islands",
          "Sierra Leone",
          "San Marino",
          "Somalia",
          "Serbia",
          "South Sudan",
          "São Tomé and Príncipe",
          "Suriname",
          "Slovakia",
          "Slovenia",
          "Sweden",
          "Seychelles",
          "Syria",
          "Saint Vincent and the Grenadines",
          "Samoa",
          "South Africa",
          "Togo",
          "Thailand",
          "Tajikistan",
          "Turkmenistan",
          "Timor-Leste",
          "Tonga",
          "Trinidad and Tobago",
          "Tunisia",
          "Turkey",
          "Tuvalu",
          "Tanzania",
          "United Arab Emirates",
          "United Kingdom",
          "Uganda",
          "Ukraine",
          "Uruguay",
          "United States",
          "Uzbekistan",
          "Vatican City",
          "Venezuela",
          "Vietnam",
          "Vanuatu",
          "Yemen",
          "Zambia",
          "Zimbabwe",
        ],
      },
      {
        type: "dropdown",
        name: "education",
        title: "What is your highest level of education?",
        isRequired: true,
        choices: [
          "No formal education",
          "Primary education (Grundschule)",
          "Secondary education (Realschule, Gymnasium)",
          "Vocational training (Berufsausbildung)",
          "Bachelor's degree",
          "Master's degree",
          "Doctorate or professional degree",
        ],
      },
      {
        type: "text",
        name: "profession",
        title: "What is your current primary occupation?",
        isRequired: true,
      },
      {
        type: "dropdown",
        name: "englishSpeakingFrequency",
        title: "How often do you speak English?",
        isRequired: true,
        choices: [
          "Never",
          "A few times a year",
          "A few times a month",
          "A few times a week",
          "Every day",
        ],
      },
      {
        type: "dropdown",
        name: "englishUnderstandingFrequency",
        title:
          "How often do you need to understand English (for example, when reading or on the internet)?",
        isRequired: true,
        choices: [
          "Never",
          "A few times a year",
          "A few times a month",
          "A few times a week",
          "Every day",
        ],
      },
      {
        type: "dropdown",
        name: "englishProficiency",
        title: "How would you rate your English proficiency?",
        isRequired: true,
        choices: [
          "Beginner (A1)",
          "Elementary (A2)",
          "Intermediate (B1)",
          "Upper-Intermediate (B2)",
          "Advanced (C1)",
          "Native Speaker (C2)",
        ],
      },
    ],
    showQuestionNumbers: "off",
  };

  // Create the survey model
  const survey = new Model(surveyJson);
  survey.focusFirstQuestionAutomatic = false;

  // Handle survey completion
  survey.onComplete.add((sender) => {
    const results = sender.data;
    console.log("Survey results:", results);

    storeJson(results, "demographics")
      .then((response) => {
        if (!response.ok) throw new Error("Failed to submit survey");
        return response.json();
      })
      .then((json) => {
        console.log("Server response:", json.message);
        navigateDelayed("/task"); // Redirect to task page
      })
      .catch((err) => {
        console.error("Error submitting survey:", err);
        navigateDelayed("/task"); // Proceed anyway (matches your finally block)
      });
  });

  return (
    <div>
      <Survey model={survey} />
    </div>
  );
};

export default Demographics;
