const style = {
  hotels: {
    headerBg: "#003580",
    headerImage: "url(img/wanderlust.jpeg)",
    primary: "#007bff",
    secondary: "#6c757d",
    accent: "#28a745",
    fontFamily: "Arial, sans-serif",
  },
  flights: {
    headerBg: "#f0f8ff",
    headerImage: "url(img/skyway.jpg)",
    primary: "#1ba0e2",
    secondary: "#00224f",
    accent: "#ffa500",
    fontFamily: "'Segoe UI', sans-serif",
  },
  cars: {
    headerBg: "#e6f2e6",
    headerImage: "url(img/driveaway.jpg)",
    primary: "#006641",
    secondary: "#00a36c",
    accent: "#ffc107",
    fontFamily: "'Roboto', sans-serif",
  },
};

const text = {
  hotels: {
    title: "Wanderlust Hotels",
    item_name: "hotel",
    slogan: "Wanderlust days and cozy nights",
    description: "Choose from cabins, houses, and more",
    exploreButton: "Explore vacation rentals",
    searchButton: "Search",
    adultLabel: "Adult",
    childrenLabel: "Children",
    roomLabel: "Room",
  },
  flights: {
    title: "SkyWay Flights",
    item_name: "flight",
    slogan: "Smooth skies and easy journeys",
    description: "Book domestic and international flights with ease",
    exploreButton: "Explore flight options",
    searchButton: "Search flights",
    adultLabel: "Adult",
    childrenLabel: "Children",
    roomLabel: "Cabin",
  },
  cars: {
    title: "DriveAway Car Rentals",
    item_name: "car",
    slogan: "Your ride, your freedom",
    description: "Find the perfect rental for your trip",
    exploreButton: "Browse car rentals",
    searchButton: "Search cars",
    adultLabel: "Driver",
    childrenLabel: "Passengers",
    roomLabel: "Car type",
  },
};

const mocks = {
  hotels: [
    {
      name: "Hotel Residenz",
      location: "Westend",
      metersFromCenter: "3.8 km",
      price: 68,
      prevPrice: 75,
      rating: 8.6,
      numReviews: 2502,
      comfort: 9.4,
      description:
        "Contemporary living, sleek hotel, stylish rooms, top-notch amenities.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "CitySmart Hotels Stadion",
      location: "Am Stadion",
      metersFromCenter: "4.2 km",
      price: 75,
      rating: 9.0,
      numReviews: 984,
      comfort: 9.4,
      description: "Style in simplicity, minimalist design, maximum comfort.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Hotel Schlossblick",
      location: "Am Schlosspark",
      metersFromCenter: "2.4 km",
      price: 84,
      rating: 9.7,
      numReviews: 2991,
      comfort: 8.6,
      description:
        "Refined luxury, sophisticated setting, exquisite accommodations, impeccable service.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "The Nordic Inn",
      location: "Markt",
      metersFromCenter: "1.5 km",
      price: 83,
      rating: 8.4,
      numReviews: 2140,
      comfort: 9.5,
      description:
        "Tranquility in a peaceful space, where comfort meets simplicity.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Mitor Hotel Mitte",
      location: "Mitte",
      metersFromCenter: "2.8 km",
      price: 56,
      prevPrice: 66,
      rating: 8.6,
      numReviews: 1139,
      comfort: 9.9,
      description:
        "Classic charm, welcoming establishment, timeless hospitality, cozy accommodations.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: true,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "City Palace",
      location: "Westend",
      metersFromCenter: "3.6 km",
      price: 79,
      rating: 7.5,
      numReviews: 2104,
      comfort: 9.5,
      description:
        "Escape to modernity, chic urban destination, cutting-edge design, vibrant atmosphere.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Le petit logement",
      location: "Stadtmitte",
      metersFromCenter: "1 km",
      price: 59,
      rating: 8.4,
      numReviews: 2140,
      comfort: 9.1,
      description: "Cozy stay, comfortable suites, warmth, relaxation.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Hotel Domicil",
      location: "Südende",
      metersFromCenter: "4.4 km",
      price: 81,
      rating: 9.8,
      numReviews: 2498,
      comfort: 9,
      description:
        "Effortless sophistication, refined elegance, impeccable details.",
      roomName: "Quadruple Room",
      freeCancellation: false,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Stella Hotel",
      location: "Westend",
      metersFromCenter: "4.7 km",
      price: 63,
      rating: 7.7,
      numReviews: 1036,
      comfort: 9.3,
      description:
        "Unwind in understated luxury, quiet escape, indulgent accommodations.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: true,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
    {
      name: "Kükennest",
      location: "Zoologischer Garten",
      metersFromCenter: "2.7 km",
      price: 84,
      rating: 8.7,
      numReviews: 1829,
      comfort: 8.8,
      description:
        "Recharge in relaxed accommodations, laid-back vibes, modern convenience.",
      roomName: "Quadruple Room",
      freeCancellation: true,
      freeAirportTaxi: false,
      freeBreakfast: false,
      beds: {
        queen: 2,
        single: 2,
        sofa: 1,
      },
    },
  ],
  flights: [
    {
      name: "Comfort Plus",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 201,
      rating: 9.7,
      numReviews: 636,
      description:
        "Comfort Plus class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: true,
    },
    {
      name: "JetSaver",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 232,
      rating: 7.6,
      numReviews: 1861,
      description: "JetSaver class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: false,
    },
    {
      name: "Sunrise Service",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 160,
      rating: 7.8,
      numReviews: 2420,
      description:
        "Sunrise Service class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: false,
      extraLegroom: false,
    },
    {
      name: "Twilight Express",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 199,
      rating: 7.5,
      numReviews: 1100,
      description:
        "Twilight Express class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: false,
      extraLegroom: true,
    },
    {
      name: "Red Eye Flight",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 212,
      rating: 9.4,
      numReviews: 1086,
      description:
        "Red Eye Flight class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: true,
    },
    {
      name: "Midday Glide",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 134,
      rating: 9.3,
      numReviews: 2250,
      description:
        "Midday Glide class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: false,
    },
    {
      name: "Morning Breeze",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 101,
      rating: 9.6,
      numReviews: 1118,
      description:
        "Morning Breeze class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: true,
    },
    {
      name: "Oceanic Flyer",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 206,
      rating: 8.2,
      numReviews: 1584,
      description:
        "Oceanic Flyer class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: true,
      extraLegroom: true,
    },
    {
      name: "Comfort Plus",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 187,
      rating: 9.2,
      numReviews: 585,
      description:
        "Comfort Plus class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: false,
      extraLegroom: false,
    },
    {
      name: "JetSaver",
      airline: "SkyWay Airways",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00m",
      price: 91,
      rating: 7.8,
      numReviews: 2219,
      description: "JetSaver class flight with competitive pricing and service",
      freeCancellation: true,
      freeMeal: false,
      extraLegroom: false,
    },
  ],
  cars: [
    {
      name: "Urban Runner",
      model: "VW Polo",
      location: "Train Station",
      metersFromCenter: "4.4 km",
      price: 51,
      rating: 7.6,
      numReviews: 442,
      description: "Urban Runner - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Adventure Pro",
      model: "Jeep Wrangler",
      location: "City Center",
      metersFromCenter: "5.6 km",
      price: 57,
      rating: 7.1,
      numReviews: 626,
      description: "Adventure Pro - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Family Van",
      model: "Renault Espace",
      location: "Airport",
      metersFromCenter: "11.6 km",
      price: 67,
      rating: 8.4,
      numReviews: 1236,
      description: "Family Van - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Mini Go",
      model: "Fiat 500",
      location: "Train Station",
      metersFromCenter: "11.6 km",
      price: 54,
      rating: 9.1,
      numReviews: 1173,
      description: "Mini Go - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "EcoCruiser",
      model: "Hyundai Ioniq",
      location: "Train Station",
      metersFromCenter: "14.5 km",
      price: 95,
      rating: 8.1,
      numReviews: 1039,
      description: "EcoCruiser - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "City Hopper",
      model: "Mini Cooper",
      location: "Train Station",
      metersFromCenter: "3.8 km",
      price: 85,
      rating: 9.7,
      numReviews: 943,
      description: "City Hopper - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Executive Line",
      model: "Audi A6",
      location: "Airport",
      metersFromCenter: "11.5 km",
      price: 72,
      rating: 7.3,
      numReviews: 550,
      description: "Executive Line - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Electric Motion",
      model: "Tesla Model 3",
      location: "Train Station",
      metersFromCenter: "11.3 km",
      price: 31,
      rating: 7.8,
      numReviews: 1477,
      description:
        "Electric Motion - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Urban Runner",
      model: "VW Polo",
      location: "Airport",
      metersFromCenter: "6.1 km",
      price: 54,
      rating: 8.8,
      numReviews: 925,
      description: "Urban Runner - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: true,
      seats: 5,
      transmission: "automatic",
    },
    {
      name: "Adventure Pro",
      model: "Jeep Wrangler",
      location: "Airport",
      metersFromCenter: "13.6 km",
      price: 72,
      rating: 8.9,
      numReviews: 317,
      description: "Adventure Pro - comfortable and reliable for everyday use",
      freeCancellation: true,
      freeInsurance: false,
      seats: 5,
      transmission: "automatic",
    },
  ],
};

const websitesData = {
  hotels: {
    site: "hotels",
    domain: "hotels.travel",
    s: style.hotels,
    t: text.hotels,
    m: mocks.hotels,
  },
  flights: {
    site: "flights",
    domain: "flights.travel",
    s: style.flights,
    t: text.flights,
    m: mocks.flights,
  },
  cars: {
    site: "cars",
    domain: "cars.travel",
    s: style.cars,
    t: text.cars,
    m: mocks.cars,
  },
} as const;

export type WebsiteData = (typeof websitesData)[keyof typeof websitesData];
export default websitesData;
